version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./tweetersphere:/app/tweetersphere/
      - ./django-cmd.sh:/app/django-cmd.sh
    depends_on:
      - db
    env_file:
      - .env
    command:  sh -c "/app/django-cmd.sh"

  
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    volumes:
    - mysql_data:/var/lib/mysql/

volumes:
  mysql_data: