# Generated by Django 5.0.2 on 2024-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
